# This is a more explicit way to define stuff and adds
# support for extra fields like help text
coming-soon:
  label: Coming Soon
  help: Coming Soon Page # Help can be applied at any level
  sections:

    meta:
      label: Page meta
      help: Meta tags for the page

      fields:
        title:
          label: Meta title of the page
          help: Will show up in the browser window or tab

    # ... but here is the longhand way of specify a section
    body:
      label: Page body
      help: The main content of the page

      # Here are each of the different field types supported
      fields:

        # The default is a textfield
        title:
          label: The title of the page
          help: Will show up as an h1

        # A textarea
        subtitle,textarea: |-
          This subtitle will populate here.
          And this will be another "paragraph".

        # WYSIWYG, CKEditor field
        content:
          type: wysiwyg # Type is declared explicitly
          value: Sito in costruzione, torna a trovarci presto!

        # An image field
        image:
          type: image
          label: Body image
          # value: /img/temp/home-marquee.jpg

        # A boolean / checkbox field
        show_image:
          type: boolean
          label: Show image instead of title
          value: 0 # Default the checkbox to "unchecked"
